iiwa_manipulator_dummy:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_timeout: 0.1
  solve_type: Distance
  position_only_ik: False
#iiwa_manipulator_dummy:
#  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#  kinematics_solver_search_resolution: 0.01
#  kinematics_solver_timeout: 0.01
#  kinematics_solver_attempts: 50
#iiwa_manipulator_dummy:
#  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
#  kinematics_solver_timeout: 0.1
#  solve_type: Distance
#  position_only_ik: False
