# An action which interpolates the trajectory planned by the OMPL MOveIt! planner

#GOAL DEFINITION

trajectory_msgs/JointTrajectory planned_trajectory

---

#RESULT DEFINITION
bool interpolation_success

---

#FEEDBACK
float64 time_left
